=== MartinMReed/signingserver/target/classes/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" elementFormDefault="qualified" jxb:version="1.0" jxb:extensionBindingPrefixes="xjc" targetNamespace="http://hardisonbrewing.org/schemas/model" xmlns="http://hardisonbrewing.org/schemas/model">

	<xs:element name="config" type="SigningConfiguration" />

	<xs:complexType name="SigningConfiguration">
		<xs:sequence>
			<xs:element name="tracker" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="salt" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="privateKey" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="authorities" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="authority" type="SigningAuthority" minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="cods" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="cod" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SigningAuthority">
		<xs:sequence>
			<xs:element name="signerId" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="url" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="clientId" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="password" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== MartinMReed/signingserver/target/classes/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://hardisonbrewing.org/schemas/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hardisonbrewing.org/schemas/model config.xsd">
	<tracker>http://isthesigningserverdown.com/submit4.4.php</tracker>
	<salt>hP62w38qysA=</salt>
	<privateKey>cB9JIMi8e+8FgQ4PN11whsRHyIw=</privateKey>
	<authorities>
		<authority>
			<signerId>RRT</signerId>
			<url>http://www.rim.net/Websigner/servlet/Runtime</url>
			<clientId>244931142</clientId>
			<password>p3xqwerty</password>
		</authority>
		<authority>
			<signerId>RBB</signerId>
			<url>http://www.rim.net/Websigner/servlet/BBApps</url>
			<clientId>244931142</clientId>
			<password>p3xqwerty</password>
		</authority>
		<authority>
			<signerId>RCR</signerId>
			<url>http://www.rim.net/Websigner/servlet/CryptoRIM</url>
			<clientId>244931142</clientId>
			<password>p3xqwerty</password>
		</authority>
	</authorities>
	<cods>
		<cod>cods/sigtool-0.cod</cod>
		<cod>cods/sigtool-1.cod</cod>
		<cod>cods/sigtool-2.cod</cod>
		<cod>cods/sigtool-3.cod</cod>
		<cod>cods/sigtool-4.cod</cod>
		<cod>cods/sigtool-5.cod</cod>
		<cod>cods/sigtool-6.cod</cod>
		<cod>cods/sigtool-7.cod</cod>
		<cod>cods/sigtool-8.cod</cod>
		<cod>cods/sigtool-9.cod</cod>
	</cods>
</config>
